# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# Set theme - required due to installation from github
theme = "congo"

baseURL = "https://www.jaredszajkowski.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true

[permalinks]
  [permalinks.page]
  #  posts = '/:year/:month/:day/:slug/'
    posts = '/posts/:slug/'
    pages = '/:slug/'
  #[permalinks.section]
  #  posts = '/posts/'
  #  pages = '/pages/'
  #  topics = '/'
  #[permalinks.taxonomy]
  #  topics = '/:slug/'

