# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNos = false
  lineNoStart = 1
  lineNumbersInTable = true
  #style = "dracula"
  tabWidth = 4

[tableOfContents]
  startLevel = 2
  endLevel = 4